// <auto-generated />
using System;
using Mal3ab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mal3ab.Migrations
{
    [DbContext(typeof(Mal3abContext))]
    partial class Mal3abContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Mal3ab.Models.Price", b =>
                {
                    b.Property<int>("price_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("price_hour")
                        .HasColumnType("decimal(5,1)");

                    b.HasKey("price_id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Mal3ab.Models.Reservation", b =>
                {
                    b.Property<int>("reservation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("approver_iduser_id")
                        .HasColumnType("int");

                    b.Property<int?>("client_iduser_id")
                        .HasColumnType("int");

                    b.Property<int?>("creator_iduser_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("from")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("price_hour")
                        .HasColumnType("decimal(5,1)");

                    b.Property<bool>("reservation_type")
                        .HasColumnType("bit");

                    b.Property<DateTime>("to")
                        .HasColumnType("datetime2");

                    b.HasKey("reservation_id");

                    b.HasIndex("approver_iduser_id");

                    b.HasIndex("client_iduser_id");

                    b.HasIndex("creator_iduser_id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Mal3ab.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mal3ab.Models.Weekly_reservation", b =>
                {
                    b.Property<int>("reservation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("client_iduser_id")
                        .HasColumnType("int");

                    b.Property<int?>("creator_iduser_id")
                        .HasColumnType("int");

                    b.Property<int>("day")
                        .HasColumnType("int");

                    b.Property<DateTime>("from")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("to")
                        .HasColumnType("datetime2");

                    b.HasKey("reservation_id");

                    b.HasIndex("client_iduser_id");

                    b.HasIndex("creator_iduser_id");

                    b.ToTable("Weekly_reservations");
                });

            modelBuilder.Entity("Mal3ab.Models.Reservation", b =>
                {
                    b.HasOne("Mal3ab.Models.User", "approver_id")
                        .WithMany()
                        .HasForeignKey("approver_iduser_id");

                    b.HasOne("Mal3ab.Models.User", "client_id")
                        .WithMany()
                        .HasForeignKey("client_iduser_id");

                    b.HasOne("Mal3ab.Models.User", "creator_id")
                        .WithMany()
                        .HasForeignKey("creator_iduser_id");

                    b.Navigation("approver_id");

                    b.Navigation("client_id");

                    b.Navigation("creator_id");
                });

            modelBuilder.Entity("Mal3ab.Models.Weekly_reservation", b =>
                {
                    b.HasOne("Mal3ab.Models.User", "client_id")
                        .WithMany()
                        .HasForeignKey("client_iduser_id");

                    b.HasOne("Mal3ab.Models.User", "creator_id")
                        .WithMany()
                        .HasForeignKey("creator_iduser_id");

                    b.Navigation("client_id");

                    b.Navigation("creator_id");
                });
#pragma warning restore 612, 618
        }
    }
}
